### ISSUE TITLE
[admin] Specify group during user creation

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-users#103]
During creation, when a user is flagged as staff but not flagged as superuser, we should force the selection of a group (operator or administrator).

**Comment by NoumbissiValere** [comment]
I think this can be done with JavaScript or model validation.  @nemesisdesign Please which method do you think is more efficient and should be used?

**Comment by nemesisdesign** [comment]
@nemesisdesign I think form validation. I also updated the description of the issue to specify that this should be enforced only for staff users.
