### ISSUE TITLE
[tests] Update TestMultitenantAdminMixin to use default operator group

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-users#106]
In this test utility code (which is reused across openwisp modules):

https://github.com/openwisp/openwisp-users/blob/cf5cd64f7d3c3515fcd0fc1f23077620b5a85964/openwisp_users/tests/utils.py#L23-L39

The test expects the permission of the operator to be defined as a class attribute.

This is obsolete, because in more recent versions of OpenWISP we added two default `auth.Group instances`: operator and administrator.

- update the test method to assign those groups
- remove `operator_permission_filters = []`
- remove `get_operator_permissions`

Open a pull request in each openwisp module to remove the `operator_permission_filters` and ensuring the new code works: https://github.com/search?q=org%3Aopenwisp+operator_permission_filters&type=Code

**Comment by niteshsinha17** [comment]
I am working on this Issue 😊

**Comment by niteshsinha17** [comment]
I think I need some more time to work on this Issue. If someone wants to work on it can go ahead.

**Comment by lehone-hp** [comment]
I will be working on this.

**Comment by lehone-hp** [comment]
@nemesisdesign after removing `get_operator_permissions` and assigning the Administrator and Operator [permissions](https://github.com/lehone-hp/openwisp-users/commit/c01c5cd4335f5d8c6fed06805ac1b79e243f3eeb), several tests keep failing with the output below.
![Screenshot from 2021-01-12 10-43-29](https://user-images.githubusercontent.com/23194068/104297395-1ace0f80-54c3-11eb-91d8-9dc2c3d0cb72.png)

Please how do I proceed from here?

**Comment by niteshsinha17** [comment]
@lehone-hp This is happening because Operation does not have permission to access those pages that's why it is giving error `Couldn't retrieve content`. We may need to add permissions to the operator for it.  Am I right @nemesisdesign ?

**Comment by niteshsinha17** [comment]
If you will remove these lines then it will not show any error.
https://github.com/openwisp/openwisp-users/blob/8a411dda5fefaee3f371412a1d249765f1333309/openwisp_users/tests/utils.py#L85-L98
But I don't think it's a solution. nemesisdesign can give a better solution for it.

**Comment by nemesisdesign** [comment]
> @lehone-hp This is happening because Operation does not have permission to access those pages that's why it is giving error `Couldn't retrieve content`. We may need to add permissions to the operator for it. Am I right @nemesisdesign ?

I think this is correct.

**Comment by lehone-hp** [comment]
Okay, I will assign the appropriate permissions and then open a PR
