### ISSUE TITLE
Superuser can't delete a regular user

### ISSUE THREAD

**Issue by okraits** [openwisp/openwisp-users#110]
When trying to delete a regular user as admin (with superuser status) I get the following message:

![grafik](https://user-images.githubusercontent.com/5543887/80746234-d27fe480-8b21-11ea-926f-a35ecb05fb2e.png)

But there's no user with more privileges.

This is openwisp-users 0.2.0.

**Comment by nemesisdesign** [comment]
Are you sure you're logged in as superuser? Maybe you're logged in as a staff user with administrator role?

**Comment by okraits** [comment]
> Are you sure you're logged in as superuser? Maybe you're logged in as a staff user with administrator role?

Of course, there are no other users besides the superuser and the user I want to delete. Also, I re-created the database from scratch to verify the issue.

**Comment by nemesisdesign** [comment]
Thanks @NoumbissiValere and @okraits, a fix is released on pypi: https://pypi.org/project/openwisp-users/0.2.2/
