### ISSUE TITLE
[users-admin] Overlapping GUI items

### ISSUE THREAD

**Issue by okraits** [openwisp/openwisp-users#111]
In the page "Change organization user" I noticed overlapping GUI items:

![grafik](https://user-images.githubusercontent.com/5543887/80746084-964c8400-8b21-11ea-8883-0471215f6ea4.png)

This is openwisp-users 0.2.0.

**Comment by atb00ker** [comment]
@okraits  Seems to be a duplicate of https://github.com/openwisp/openwisp-users/issues/93
Can you please try refreshing your cache? :smile:

**Comment by nemesisdesign** [comment]
Looks solved to me, re-open if not.
