### ISSUE TITLE
[docs] Remove redundant steps for installing for development

### ISSUE THREAD

**Issue by pandafy** [openwisp/openwisp-users#113]
Steps for installing `openwisp-users` for development are redundant in `README.rst`.

**Comment by nemesisdesign** [comment]
You mean what is written here: https://github.com/openwisp/openwisp-users#install-development-version is repeated afterwards?

The first one can be removed I think.

**Comment by pandafy** [comment]
Yes @nemesisdesign . (Getting permalink for rendered document is not straight forward as with other code. :sweat_smile: )
These specific lines should be removed
https://github.com/openwisp/openwisp-users/blob/1ad50823b8f63f58b62afa1361145854e624f680/README.rst#L58-L65

**Comment by nemesisdesign** [comment]
@pandafy you can proceed if you want

**Comment by pandafy** [comment]
I think this can be a good first issue for new contributors. I don't feel there is an urgency to fix it, let me know if there is. I will create a patch for it.

**Comment by codesankalp** [comment]
@pandafy 
please see this : https://github.com/openwisp/openwisp-users/pull/118
