### ISSUE TITLE
[admin] Allow administrators to delete other users + other related improvements

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-users#128]
The following permissions are missing from the administrator group definition (`is_staff=True, is_superuser=False, group=administrator`):

- delete users
- add/change/delete email address

An administrator should not be able to delete a user if the user is owner of an organization (defined with `OrganizationnOwner` which we are not using now, but makes sense to start supporting it).

An administrator already can't see/edit/delete superusers, so we don't need to do anything there.

After this, it would be great to address also #103

**Comment by NoumbissiValere** [comment]
@nemesisdesign please when you talk of `Administrators` being able to `delete/change/add email address`, are we referring to their email addresses only or plus the email addresses of other `Administrators`  excluding `superusers`

**Comment by nemesisdesign** [comment]
@NoumbissiValere 

> @nemesisdesign please when you talk of `Administrators` being able to `delete/change/add email address`, are we referring to their email addresses only or plus the email addresses of other `Administrators` excluding `superusers`

only add the permissions, once that is done they'll be able to manage the email addresses of the users, now they can't.
