### ISSUE TITLE
[admin] Allow administrator role to access organization admin

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-users#143]
- add the permission to change organizations to the administrator role
- ensure only only users which are managers of the org can change it (override has_change_permission)
- ensure has_add_permission and has_delete_permission only return True for superusers
- ensure only superusers and organization owners can change the organization owner inline
- ensure only superusers can add/delete the organization owner inline
- briefly document this in the README and add the link to the new section in the change log

**Comment by NoumbissiValere** [comment]
> * ensure only superusers and organization owners can change the organization owner inline
> * ensure only superusers can add/delete the organization owner inline

@nemesisdesign for this point to be achieved, we need to merge #140 first

**Comment by nemesisdesign** [comment]
> > * ensure only superusers and organization owners can change the organization owner inline
> > * ensure only superusers can add/delete the organization owner inline
> 
> @nemesisdesign for to achieve this points, we need to merge #140 first

Merged.
