### ISSUE TITLE
[bug] Organization creation form can't take org owner 

### ISSUE THREAD

**Issue by atb00ker** [openwisp/openwisp-users#149]
When filling the organization creation form, if you select `OrganizationUser` it will never be a part of the organization that you are creating, hence you'll always get the error: "The selected user is not member of this organization."

Hence, I think it needs to be removed from the add organization form.

**Comment by NoumbissiValere** [comment]
@atb00ker this makes sense. But what if, instead of removing it, at the back, we first create the org_user before the org_owner?

**Comment by atb00ker** [comment]
@NoumbissiValere We will have to take care of a lot of edge cases, for example: if user closes the tab before saving, now we have an organization created but the user thinks it's not created as they never clicked save.

Similarly, I can think of multiple cases where saving an organization without clicking save could result to confusion and dealing with such cases will make the code really complicated. I think would this wouldn't honor KISS (Keep it simple, silly) philosophy.

What do you think about such cases?

**Comment by NoumbissiValere** [comment]
🤔 some of them crossed my mind but I was thinking of passing through the `post_save` of `organization`. 
You are right. We can't implement this without violating the KISS philosophy.  
@nemesisdesign I think @atb00ker is right about us removing this inline from the add form.

**Comment by nemesisdesign** [comment]
Yes, the best option is to remove OrganizationOwnerInline in the add form, it can be done by overriding the `get_inlines` method.
@atb00ker could you help out with this?

**Comment by atb00ker** [comment]
`get_inlines` was added in `django 3.0`, using it means dropping previous versions. Django 2.2 was LTS and supported till April 2022, so I think we should take another approach for it! :smile:

**Comment by NoumbissiValere** [comment]
@atb00ker what of something similar to this https://github.com/openwisp/openwisp-users/blob/master/openwisp_users/admin.py#L409

**Comment by nemesisdesign** [comment]
@atb00ker I always forget about that.. even though we could drop support for django 2.2, but it would mean more work for us to drop support also in other modules to make it consistent, so ok for finding another way.

@NoumbissiValere that line of code, now that I look at it, I wonder if it can be problematic. It looks like it modifies self.inlines which should be a class attribute, this would mean that if that line is executed, the inline is made readonly also for other users, which is a bug.

**Comment by nemesisdesign** [comment]
@atb00ker @NoumbissiValere I think we can use `get_inline_instances`, which is present also in django 2.2:
https://github.com/django/django/blob/stable/2.2.x/django/contrib/admin/options.py#L585-L599

Actually we are already using it to show the `OrganizationUserInline` in the add user page: https://github.com/openwisp/openwisp-users/blob/master/openwisp_users/admin.py#L386-L400

@NoumbissiValere I think we should use a similar approach to replace `self.inlines[1] = OrganizationUserInlineReadOnly, which looks fragile to me, if we change the orders of inlines for example, that line will cause issues which will eat time only to understand what's going wrong.

**Comment by atb00ker** [comment]
@atb00ker @NoumbissiValere Fixed both the issues in https://github.com/openwisp/openwisp-users/pull/154 and  https://github.com/openwisp/openwisp-users/pull/155 respectively.

**Comment by apsideproj** [comment]
Hey @atb00ker @nemesisdesign I came across this when attempting to do something specific for my project. I want to allow people to create their own organizations and accounts on a sign up page. I understand this is possible using django-organizations but is there any built in support in openwisp-users? The user signing up should become the organization owner and an organization user at the same time.

**Comment by nemesisdesign** [comment]
@apsideproj it's not imeplemented but if you implement it you're welcome to send a patch.
