### ISSUE TITLE
[api] Add reusable mechanism to validate organization membership

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-users#150]
In each module where we have an API, we are implementing the validation of the organization membership of a user differently and this is not good.

We need a general and reusable solution for this.

I think we can use `permission_classes` for this and create some classes like:

`isOrganizationMember`, `isOrganizationManager`, `isOrganizationOwner`.

We have to allow specifying the name of the organization field, eg:

```python
permission_classes = (isOrganizationMember,)
organization_field = 'organization'  # default
```

In case the organization field is on a parent element, we should be able to do the following:

```python
permission_classes = (isOrganizationMember,)
organization_field = 'device__organization'
```

**Comment by atb00ker** [comment]
I don't understand the usage of `organization_field = 'organization'`
Do we want these classes to be specific for user model or a general function to check for any model like `Devices` etc?
