### ISSUE TITLE
[bug] Deleting an OrganizationUser instance may raise exception

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-users#165]
Try the following:

- log in as superuser
- create an organization
- create an user for the new organization (will be flagged as owner)
- try deleting the `OrganizationUser` relationship

This exception is raised:

```OwnershipRequired
Cannot delete organization owner before organization or transferring ownership.
```

Expected result:

Instead of an exception being raised, an error should be displayed in the UI: eg `ProtectedError` should do this.

**Comment by NoumbissiValere** [comment]
Here is my proposed solution:

- Raise ProtectedError in `base.models.OrganizationUser.delete()`
- Catch this exception in `admin.py` and update the `admin template` with the appropriate message

**Comment by nemesisdesign** [comment]
> @nemesisdesign why don't we delete the `organizationOwner` associated with this `OrganizationUser` along with it?
> 
> And pass ownership to the next oldest User?

Because the user may not know they're deleting an owner, if we do that, they may delete an owner inadvertently.

**Comment by NoumbissiValere** [comment]
Ok. Here is a solution I am proposing.

- The change page of such `org-user` should not have the delete permission and should display a message explaining why i can't be deleted
- If deletion is done through `delete_selected`, `org-users` which belong to `org-owners` should not be deleted and  should display a message explaining why they were not deleted.

**Comment by nemesisdesign** [comment]
> Ok. Here is a solution I am proposing.
> 
> * The change page of such `org-user` should not have the delete permission and should display a message explaining why i can't be deleted

What about just catching the exception and displaying a message using the django message framework instead?

> * If deletion is done through `delete_selected`, `org-users` which belong to `org-owners` should not be deleted and  should display a message explaining why they were not deleted.

Sounds good.

**Comment by NoumbissiValere** [comment]
> What about just catching the exception and displaying a message using the django message framework instead?

👍
