### ISSUE TITLE
[bug] OrganizationOwner shouldn't be allowed to be is_admin=False

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-users#166]
Create an organization user which becomes owner of an organization.

Try to flag it as OrganizationUser(is_admin=False).

The system allows to do this but it shouldn't, it's confusing, because the user will keep being recognized as owner.

The correct behavior would be to raise a ValidationError which says the user is owner of this organization and cannot be downgraded.

**Comment by NoumbissiValere** [comment]
@nemesisdesign how about making `is_admin` of `org_user` which belongs to `org_owner` read-only instead?

**Comment by NoumbissiValere** [comment]
> @nemesisdesign how about making `is_admin` of `org_user` which belongs to `org_owner` read-only instead?

On a second thought, I don't think this method will be the best because, users might be confused with why they can't edit the `is_admin` field. 

So I think the best thing to do is to use the `ValidationError` exception. I will implement this

**Comment by nemesisdesign** [comment]
> > @nemesisdesign how about making `is_admin` of `org_user` which belongs to `org_owner` read-only instead?
> 
> On a second thought, I don't think this method will be the best because, users might be confused with why they can't edit the `is_admin` field.
> 
> So I think the best thing to do is to use the `ValidationError` exception. I will implement this

Yes, it's the simplest thing to do at the moment, let's go for this now. If later on we find we need to improve it further we'll do it.
