### ISSUE TITLE
[admin] Add a human readable value for empty org selection

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-users#171]
When the organization selection is optional, it means that leaving it empty makes that object available for all the organizations in the system.

Right now, this is not intuitive at all. We could use some admin form magic to replace the empty string with something like: `Shared systemwide (no organization)`.

**Comment by devkapilbansal** [comment]
> When the organization selection is optional, it means that leaving it empty makes that object available for all the organizations in the system.
> 
> Right now, this is not intuitive at all. We could use some admin form magic to replace the empty string with something like: `Shared systemwide (no organization)`.

@nemesisdesign I setup the project locally by following instructions. But I don't think that the organisation selection is optional. Can you please look into this again and elaborate the issue?

**Comment by Purhan** [comment]
> > When the organization selection is optional, it means that leaving it empty makes that object available for all the organizations in the system.
> > Right now, this is not intuitive at all. We could use some admin form magic to replace the empty string with something like: `Shared systemwide (no organization)`.
> 
> @nemesisdesign I setup the project locally by following instructions. But I don't think that the organisation selection is optional. Can you please look into this again and elaborate the issue?

@devkapilbansal I've been working on this issue and I'm pretty close to a patch :smile: however, I didn't claim this so that's on my part. Would you like to leave this? For your question, yes, the sample app we're using currently has 2 models: `Book` and `Shelf`, and these both have mandatory organization field.

**Comment by devkapilbansal** [comment]
Okay @Purhan you can take this up. But if the organisation field is not optional, then does this issue makes sense?

**Comment by Purhan** [comment]
> Okay @Purhan you can take this up. But if the organisation field is not optional, then does this issue makes sense?

Yes, because there may be other modules relying on `openwisp-users` where some models have it optional.
