### ISSUE TITLE
[deps] Drop support for Django 2.2

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-users#180]
Drop support for Django 2.2 and remove any compatibility shims for that version in the repository.

**Comment by robd003** [comment]
Isn't that the currently active LTS release of Django?

**Comment by nemesisdesign** [comment]
@robd003 yes, but we don't have the same amount of contributors, maintainers and resources as the Django Software Foundation does (not that they surf in gold waters, but at least they're more supported than us), keeping support for multiple django versions costs time and money and at the moment if I have to choose between advancing the project towards its goals and maintaining compatibility with multiple django versions I must choose the former to keep the project on track with its mission.
