### ISSUE TITLE
[docs] Several broken links in "Extend openwisp-users" section 

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-users#187]
I found out several links in [Extend openwisp-users](https://github.com/openwisp/openwisp-users#extend-openwisp-users) which link code samples from openwisp-users are broken (return 404). We should review all the links one by one and fix the broken ones.

**Comment by Shagunjain10** [comment]
I would like to work on this issue.

**Comment by NoumbissiValere** [comment]
You can go ahead @Shagunjain10
