### ISSUE TITLE
Remove typographic error for backwards compatibility in openwisp-users 0.5

### ISSUE THREAD

**Issue by devkapilbansal** [openwisp/openwisp-users#194]
The typographic error in  this code should be removed in 0.5 release

https://github.com/openwisp/openwisp-users/blob/1ff86e27ffb5764e60c340da234fbcb0507a0aeb/openwisp_users/settings.py#L4-L15

**Comment by nemesisdesign** [comment]
You can proceed if you like, so we can release the 0.5 #195.
