### ISSUE TITLE
[feature] Allow logging in with phone number, email or username

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-users#206]
Right now is only possible to log in with the username, but nowadays email and phone numbers are widely used.

We need to create an authentication backend that allows authenticating with any of the following:

- username
- email
- phone number

And of course, password.

Important points:

- [ ] the string supplied for username, email or phone number must be not empty.
- [ ] we could use an OR query, in order of precedence: get user with this email or this phone number or this username
- [ ] it's possible the query will return multiple results, the precedence of the previous point should be respected: write a test in which user A has username: user@test.com and user B has email user@test.com, test the authentication backend and ensure user B gets authenticated correctly
- [ ] write a similar test like the one before but with a phone number

**Comment by pandafy** [comment]
> * it's possible the query will return multiple results, the precedence of the previous point should be respected: write a test in which user A has username: [user@test.com](mailto:user@test.com) and user B has email [user@test.com](mailto:user@test.com), test the authentication backend and ensure user B gets authenticated correctly
> * [ ]  write a similar test like the one before but with a phone number

We can just make such occurrence obsolete by putting regex in place which ensure that user can't put an email address or mobile number(a username should contain atleast one alphabet) in username field.

We should explore whether django-allauth could do the heavy lifting for us instead of creating our own authentication backend.

**Comment by NoumbissiValere** [comment]
> > * it's possible the query will return multiple results, the precedence of the previous point should be respected: write a test in which user A has username: [user@test.com](mailto:user@test.com) and user B has email [user@test.com](mailto:user@test.com), test the authentication backend and ensure user B gets authenticated correctly
> > * [ ]   write a similar test like the one before but with a phone number
> 
> We can just make such occurrence obsolete by putting regex in place which ensure that user can't put an email address or mobile number(a username should contain atleast one alphabet) in username field.

@pandafy we want to able to put an `email` or a `phone number` in the place of `username` and still get logged in.

**Comment by pandafy** [comment]
> @pandafy we want to able to put an `email` or a `phone number` in the place of `username` and still get logged in.

Thanks for clearing out @NoumbissiValere :smile:

**Comment by nemesisdesign** [comment]
@pandafy changing the authentication backend is the standard practice, why do you think is better doing it differently?
