### ISSUE TITLE
[bug] Group has not been registered with django-reversion

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-users#214]
This shows up in instances installed via ansible-openwisp2 but can be replicated in the dev env.

**How to replicate**:

- add `reversion` to INSTALLED_APPS, install django-reversion if you don't have it installed in your virtualenv already, in openwisp-users is optional
- go to groups, open a group, (eg: administrator), make some changes, save, repeat the process again
- click on the "history" button in the upper right part of the page
- different revisions will appear, click on any

**Expected outcome**:

Page with the revision appears.

**Actual outcome**:

```
<class 'django.contrib.auth.models.Group'> has not been registered with django-reversion
```

**Comment by nemesisdesign** [comment]
Fun fact, trying to register `Group` manually yields the opposite exception:

```
>>> from reversion import revisions
>>> revisions.register(Group)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    revisions.register(Group)
  File "/opt/openwisp2/env/lib/python3.8/site-packages/reversion/revisions.py", line 406, in register
    return register(model)
  File "/opt/openwisp2/env/lib/python3.8/site-packages/reversion/revisions.py", line 373, in register
    raise RegistrationError("{model} has already been registered with django-reversion".format(
reversion.errors.RegistrationError: <class 'openwisp_users.models.Group'> has already been registered with django-reversion
```

**Comment by nemesisdesign** [comment]
Oh I see now, Group is being interpreted in two different ways:

- `openwisp_users.models.Group`: registered
- `django.contrib.auth.models.Group`: not registered

**Comment by niteshsinha17** [comment]
> This shows up in instances installed via ansible-openwisp2 but can be replicated in the dev env.
> 
> **How to replicate**:
> 
> * add `reversion` to INSTALLED_APPS, install django-reversion if you don't have it installed in your virtualenv already, in openwisp-users is optional
> * go to groups, open a group, (eg: administrator), make some changes, save, repeat the process again
> * click on the "history" button in the upper right part of the page
> * different revisions will appear, click on any
> 
> **Expected outcome**:
> 
> Page with the revision appears.
> 
> **Actual outcome**:
> 
> ```
> <class 'django.contrib.auth.models.Group'> has not been registered with django-reversion
> ```

@nemesisdesign I was able to replicate this but when I run `./manage.py createinitialrevisions` I got the expected outcome.

**Comment by Purhan** [comment]
> I was able to replicate this but when I run ./manage.py createinitialrevisions I got the expected outcome.

Are you sure about this? This had no effect for me.
