### ISSUE TITLE
```pip install openwisp-users``` showing errors for python 2.7

### ISSUE THREAD

**Issue by ShubhamKushwah** [openwisp/openwisp-users#22]
IOError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/typing.pyc'

pip3 will do the work, I have created a pull request for the same.

**Comment by ShubhamKushwah** [comment]
I think to grant the permission to change to that system folder we need to run this:

`
sudo chown -R $USER /Library/Python/2.7
`

**Comment by ShubhamKushwah** [comment]
If issues are still there, it's probably because of El Captain Mac users.
This should work for them.

`
brew install python
`

**Comment by nemesisdesign** [comment]
This is a system issue and not a code issue. Thanks for reporting.
