### ISSUE TITLE
[bug] Regression: opening non existing user ID raises an exception

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-users#228]
How to replicate the issue:

**Try opening:**

- `http://localhost:8000/admin/openwisp_users/user/15f0345b-b9c1-44b2-b674-0deac5c7c816/change/`
- `http://localhost:8000/admin/openwisp_users/user/WRONG/change/`

**Expected outcome:** 404, no exception raised

**Actual outcome:** exception is raised.

**Cause:**

https://github.com/openwisp/openwisp-users/blob/8b4e84a665f0d53ddf3e96fb9a52d0641bd1e74b/openwisp_users/admin.py#L411

**Solution:**

- write a failing test for both cases
- handle both exceptions and raise Http404()

**Comment by Saurav-Shrivastav** [comment]
I would like to take this up! Can it be assigned to me? @nemesisdesign
