### ISSUE TITLE
[bug] Don't allow filter classes to be used without authentication

### ISSUE THREAD

**Issue by Purhan** [openwisp/openwisp-users#229]
https://github.com/openwisp/openwisp-controller/pull/374#pullrequestreview-581968990

If used in views without `IsAuthenticated` permission, the filter classes will raise an exception.

**Comment by nemesisdesign** [comment]
@Purhan maybe our classes can inherit and extend `IsAuthenticated`, so we get this check for free, without having to specify again `IsAuthenticated`? Since it's implied that the user needs to be authenticated for this feature to work.

**Comment by Purhan** [comment]
> @Purhan maybe our classes can inherit and extend `IsAuthenticated`, so we get this check for free, without having to specify again `IsAuthenticated`? Since it's implied that the user needs to be authenticated for this feature to work.

I'm not sure how that's possible since most of the logic for `permission_classes` exist in `APIView` class of DRF and not the permission classes themselves.
Maybe we could do the following:

- Inherit from `rest_framework.views.APIView`
- Override the following function:
```python
def get_permissions(self):
        try:
            return super().get_permissions() + [IsAuthenticated()]
        except TypeError:
            return [IsAuthenticated()]
```

PR incoming soon
