### ISSUE TITLE
[cleanup] Clean format=api HTTP_AUTHORIZATION and mixed quotes in test_filter_classes.py 

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-users#242]
The `tests/testapp/tests/test_filter_classes.py` suffers of the following problems:

- calls to the browsable API are done in a not clean way, we should do those calls as indicated in https://github.com/openwisp/openwisp-users/pull/239#discussion_r618058751
- quoting style is mixed, we should keep consistency and use only single quotes whenever possible

**Comment by hannasalam** [comment]
I would like to work on this if it's not been taken

**Comment by ManishShah120** [comment]
@hannasalam Yes, you can work on it.

**Comment by nemesisdesign** [comment]
@hannasalam go for it :+1:
