### ISSUE TITLE
[Bug] Include the objects with org=None, while filtering serilaizer fileds based on the organization of an user

### ISSUE THREAD

**Issue by ManishShah120** [openwisp/openwisp-users#247]
https://github.com/openwisp/openwisp-users/blob/747ac34ac59c7fee843f8ad250cc5d12292c722b/openwisp_users/api/mixins.py#L137-L140

@nemesisdesign , @atb00ker with this line of code we are trying to filter out other `ForeignKey` related field other than `organization` field, based on the organization of a user, But mostly all of such fields has an option to create objects as shared org(organization=None). eg.:- templates, CA, etc.. But this LOC only returns the object belonging to an organization, excluding the objects whose organization is set to None.

Will it not be better, if we include the shared objects along with these.

CC: @Purhan

**Comment by atb00ker** [comment]
I think we can include `organization=None` objects in this result, but let @nemesisdesign also check it once, you might create a tentative WIP PR if this a blocker somewhere! :smile:

**Comment by nemesisdesign** [comment]
Thanks @ManishShah120, let's clarify, because I am not sure I understood.

Non superusers should be able to select shared objects when creating/editing objects via the API, eg:

- a user shall be able to assign a shared template to a device
- a user shall be able to create a template of type "VPN client" which relates to a shared VPN

Is it clear?

Is this bug you are describing preventing a user from doing that? If yes, definitely we must fix it.

**Comment by ManishShah120** [comment]
Yes, you are right, currently only those objects are returned which belongs to any organization. excluding the objects having organization set to `None` (i.e., shared objects).

**Comment by nemesisdesign** [comment]
@ManishShah120 @atb00ker @Purhan what do you think about something like the following:

```diff
diff --git a/openwisp_users/api/mixins.py b/openwisp_users/api/mixins.py
index 992223f..87fdfa2 100644
--- a/openwisp_users/api/mixins.py
+++ b/openwisp_users/api/mixins.py
@@ -14,6 +14,7 @@ class FilterByOrganization:
 
     permission_classes = [IsAuthenticated]
     organization_lookup = 'organization__in'
+    filter_shared = False
 
     @property
     def _user_attr(self):
@@ -26,8 +27,11 @@ class FilterByOrganization:
         return self.get_organization_queryset(qs)
 
     def get_organization_queryset(self, qs):
+        organization_list = getattr(self.request.user, self._user_attr)
+        if self.filter_shared:
+            organization_list = organization_list + [None]
         return qs.filter(
-            **{self.organization_lookup: getattr(self.request.user, self._user_attr)}
+            **{self.organization_lookup: organization_list}
         )
```

**Comment by atb00ker** [comment]
That looks good to me! :smile:

**Comment by ManishShah120** [comment]
@nemesisdesign, @atb00ker I tried implementing it, but it didn't resolve the issue, since we need this for serializer classes, and the changes made here are being inherited only to those mixins which are designed to be inherited to in the views classes.

I tried doing something like this(also this was suggested by @atb00ker in REST API and it works here):-
```diff
diff --git a/openwisp_users/api/mixins.py b/openwisp_users/api/mixins.py
index 992223f..c061cc6 100644
--- a/openwisp_users/api/mixins.py
+++ b/openwisp_users/api/mixins.py
@@ -1,5 +1,6 @@
 import swapper
 from django.core.exceptions import ValidationError
+from django.db.models import Q
 from rest_framework.exceptions import NotFound
 from rest_framework.permissions import IsAuthenticated
 
@@ -135,9 +136,10 @@ class FilterSerializerByOrganization:
                 )
                 continue
             try:
-                self.fields[field].queryset = self.fields[field].queryset.filter(
-                    **{self.organization_lookup: organization_filter}
-                )
+                query = Q(organization=None)
+                for org in organization_filter:
+                    query |= Q(organization=org)
+                self.fields[field].queryset = self.fields[field].queryset.filter(query)
             except AttributeError:
                 pass
```
I am not sure where this may break. :thinking:

**Comment by nemesisdesign** [comment]
@ManishShah120 yes sorry my suggestion pointed to the wrong class but I believe you can use almost the exact same code.
Try to use "in" instead of chaining several "or", the result is easier to read.

You're looping over the organizations and chaining several "or", but can be done simply by adding None to the `organization_filter` list. It should be possible to disable this since it's not required in every serializer. Please follow the suggestion I've given above.

**Comment by ManishShah120** [comment]
@nemesisdesign It is not returning the shared objects after adding `None`, to the `organization_filter` list, the results remains same, this is what I did as you suggested:-
```diff
diff --git a/openwisp_users/api/mixins.py b/openwisp_users/api/mixins.py
index 992223f..8fc0d2f 100644
--- a/openwisp_users/api/mixins.py
+++ b/openwisp_users/api/mixins.py
@@ -117,6 +117,7 @@ class FilterSerializerByOrganization:
     """
 
     organization_lookup = 'organization__in'
+    filter_shared = True
 
     @property
     def _user_attr(self):
@@ -126,7 +127,7 @@ class FilterSerializerByOrganization:
         user = self.context['request'].user
         if user.is_superuser:
             return
-        organization_filter = getattr(user, self._user_attr)
+        organization_filter = set(getattr(user, self._user_attr))
         for field in self.fields:
             if field == 'organization':
                 self.fields[field].allow_null = False
@@ -135,6 +136,8 @@ class FilterSerializerByOrganization:
                 )
                 continue
             try:
+                if self.filter_shared:
+                    organization_filter.add(None)
                 self.fields[field].queryset = self.fields[field].queryset.filter(
                     **{self.organization_lookup: organization_filter}
                 )
```
also, it is good to convert the org_list to `set`, because after each iteration `None` will be added to the list. But still this approach is not working


I did a little tweak in the previous code to include the `filter_shared` flag:-
```diff
diff --git a/openwisp_users/api/mixins.py b/openwisp_users/api/mixins.py
index 992223f..f4925d2 100644
--- a/openwisp_users/api/mixins.py
+++ b/openwisp_users/api/mixins.py
@@ -1,5 +1,6 @@
 import swapper
 from django.core.exceptions import ValidationError
+from django.db.models import Q
 from rest_framework.exceptions import NotFound
 from rest_framework.permissions import IsAuthenticated
 
@@ -117,6 +118,7 @@ class FilterSerializerByOrganization:
     """
 
     organization_lookup = 'organization__in'
+    filter_shared = True
 
     @property
     def _user_attr(self):
@@ -135,9 +137,12 @@ class FilterSerializerByOrganization:
                 )
                 continue
             try:
-                self.fields[field].queryset = self.fields[field].queryset.filter(
-                    **{self.organization_lookup: organization_filter}
-                )
+                query = Q()
+                if self.filter_shared:
+                    query = Q(organization=None)
+                for org in organization_filter:
+                    query |= Q(organization=org)
+                self.fields[field].queryset = self.fields[field].queryset.filter(query)
             except AttributeError:
                 pass
```

Am I missing something in the previous approach if not, then should we go the second approach.

**Comment by nemesisdesign** [comment]
@ManishShah120 you're right, the following is not effective:

```
Template.objects.filter(organization__in=user.organizations_managed + [None])
```

I forgot that the ORM has its own filter for checking for NULL values: `isnull`, therefore, this works (I just tested it):

```python
from django.db.models import Q
Template.objects.filter(Q(organization__in=user.organizations_managed) | Q(organization__isnull=True))
```

Therefore along the lines of the following code should work:

```python
conditions = Q(
    **{self.organization_lookup: organization_filter}
)
if self.filter_shared:
    conditions |= Q(organization__isnull=True)

self.fields[field].queryset = self.fields[field].queryset.filter(conditions)
```
