### ISSUE TITLE
[ux] User edit: the password change link is not easy to spot

### ISSUE THREAD

**Issue by EasyNetDev** [openwisp/openwisp-users#257]
Hi,

I've notice that I don't have any options to change a user password. How can I enable this form?

![No Password Change Form](https://user-images.githubusercontent.com/1823016/120601374-856fef80-c452-11eb-90cf-b60c6f96f2d4.PNG)

**Comment by nemesisdesign** [comment]
I improved this in the openwisp-utils admin theme to at least show the link of a different color for now, it will be included in the next release.

Let's leave this open though so that we can change the link to a button in the near future.

**Comment by pandafy** [comment]
In new theme of OpenWISP, there is a button inside user widget. I believe this can be closed. 

![Screenshot from 2022-01-26 22-01-55](https://user-images.githubusercontent.com/32094433/151205263-4d04fc3c-cc40-454e-8732-6aa820335d3e.png)

**Comment by nemesisdesign** [comment]
> In new theme of OpenWISP, there is a button inside user widget. I believe this can be closed.
> 
> ![Screenshot from 2022-01-26 22-01-55](https://user-images.githubusercontent.com/32094433/151205263-4d04fc3c-cc40-454e-8732-6aa820335d3e.png)

@pandafy the link to change the password is to change your own password, while the issue deals with the link to change the password of any user.

**Comment by EasyNetDev** [comment]
Hi @pandafy, check my initial post. As @nemesisdesign said, is about the password for any user when you are administrator, not the password for the user itself.

**Comment by pandafy** [comment]
Thanks for clarification Federico and Adrian. I completely misunderstood the issue.

**Comment by nemesisdesign** [comment]
This is solved in the latest version of openwisp-utils:

![Screenshot from 2022-02-15 12-36-11](https://user-images.githubusercontent.com/841044/154095318-5f219ad1-35fc-469d-8c74-7c7b00f3e900.png)
