### ISSUE TITLE
[bug] Add permission to view organizations to operator

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-users#276]
Add permission to view organizations to operator (otherwise they cannot see their own organization in select2 autocomplete fields).

**Comment by harsh-9in** [comment]
hi can i work on this issue ?

**Comment by nemesisdesign** [comment]
> hi can i work on this issue ?

Go for it! If you have questions please reach us at https://gitter.im/openwisp/general.

**Comment by pandafy** [comment]
Hey @harsh-9in are you still working on this? If you are stuck, feel free to ask for help.
