### ISSUE TITLE
[models] Ensure emails are unique

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-users#28]
~~I assumed that the default django user model had a unique constraint on the email field, but I was wrong.~~

~~We need to add this.~~

After further testing and thought I concluded that we can't do this or we won't be able to generate freeradius users with no email address.

We can't add a database constraint but we can add application validation logic which checks that if a user has an email set, no other user except him has the same email, otherwise raise a `ValidationError`.
Actually, if the blank email is set to `None`, the unique constraint error shouldn't be triggered so that may be feasible.

**Comment by anurag-ks** [comment]
![screenshot-2018-8-7 add user openwisp2 admin](https://user-images.githubusercontent.com/3973075/43781600-e354ed6c-9a7a-11e8-9f3d-8513b0c400f1.png)

But I wasn't able to add same email, while adding a new user.

**Comment by nemesisdesign** [comment]
@anurag-ks that's because of @R9295's patch #26

**Comment by nemesisdesign** [comment]
After further testing and thought I concluded that we can't do this or we won't be able to generate freeradius users with no email address.

We can't add a database constraint but we can add application validation logic which checks that if a user has an email set, no other user except him has the same email, otherwise raise a `ValidationError`.

**Comment by NoumbissiValere** [comment]
@nemesisdesign please i don't understand what is needed here. when i looked at the patch at #26 , i see the patch tries solves by problem by validating if the email already exist or not. Please can you through more light?

**Comment by NoumbissiValere** [comment]
or do you want a validation to be written at the level of `Users` model or how?

**Comment by jeffysam6** [comment]
anyone working on it?

**Comment by NoumbissiValere** [comment]
@jeffysam6 the pull request up there means someone is working on the issue already. :smile:
