### ISSUE TITLE
[bug] token endpoint is different

### ISSUE THREAD

**Issue by atb00ker** [openwisp/openwisp-users#303]
The [token endpoint](https://github.com/openwisp/openwisp-users/blob/master/openwisp_users/api/urls.py#L49) has `/user/`, rest of all of them have `/users/`.

I think this is a mistake, need to verify and fix.

**Comment by atb00ker** [comment]
@nemesisdesign should we fix it now? I fear some people must be using it already! :smile:

**Comment by nemesisdesign** [comment]
@atb00ker it's definitely a mistake and we need to fix it, thanks for reporting! :+1:

**Comment by ashutosh887** [comment]
@nemesisdesign 
Please assign this Issue to me!

**Comment by atb00ker** [comment]
@ashutosh887 you don't need to wait for an assignment, please feel free to start working on it! 😄

**Comment by ashutosh887** [comment]
Sure @atb00ker 
I'm working on it
