### ISSUE TITLE
[groups] Add default "operator" and "admin" group

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-users#31]
We should add two default groups:

- "operator" will be the group with permissions to see the basic OpenWISP objects needed to manage an organization (although each default permission available in this group should be added by each openwisp2 module, for example, the controller should add to this group the permissions to edit devices and templates, the radius module should add to this group the permissions to edit the radius related objects)
- "user manager" will have permission to manage users of their organization (although work is neeed to implement this in #32 and #34)

Other notes:
- operators won't have user editing permissions
- user managers will have permission to add/edit users so they must be able to assign groups to new users
- so groups have to be editable also by staff users (operators won't be able to change their group because they don't have permissions to edit user details)
- the important thing is that user managers can't create or change groups they can only choose from a predefined list of groups

**Comment by R9295** [comment]
Ill take this up. Can't assign myself though.

**Comment by nemesisdesign** [comment]
@R9295 :+1: I added you
