### ISSUE TITLE
[admin] Allow non-superadmins to manage their own users

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-users#32]
Users which are not a superadmins but have permissions to edit users should work be able to do so in the following way:

- [x] should be able to see and edit users of the organizations they are member of
- [ ] should not be able to see `is_superuser` column in list
- [ ] should not be able to see `is_superuser` field in change form (now is readonly)
- [ ] should be able to add new users but only set them as members of their organization
- [ ] when editing, they shouldn't be able to set users as members of other organizations they are not member of, actually the organization select should only allow them to select one of their orgs

I started some of this in branch https://github.com/openwisp/openwisp-users/tree/issues/32 but I don't have time to finish all these items, help is greatly appreciated.

**EDIT**: follow up with list of things done and to do on https://github.com/openwisp/openwisp-users/pull/38

**Comment by atb00ker** [comment]
1. Should an operator be allowed to create users without any organisation?
2. Should other organisations be visible to operators?
3. Should operator be allowed to see other organisation owners?
4. However users are not visible to operator from `User` list but still visible from `Organization users`, i think that's unintentional, right? i should implement `get_queryset` logic for `Organization user` as well, right?

**Comment by nemesisdesign** [comment]
@atb00ker:

Premise, I forgot to tell you I found out this issue: https://github.com/openwisp/openwisp-utils/issues/14
I think it makes more sense to keep the multi-tenancy features (and their tests) in this module rather than openwisp-utils, keep in mind this when working on this issue because you may likely have to edit some of that code.

I was writing a very long reply but I wanted to shorten it: I think I'm either misunderstanding you or something may not be clear.
In this issue I want to focus on `openwisp_users.admin.UserAdmin`, the other admin classes like  `OrganizationAdmin`, `OrganizationUserAdmin`, `OrganizationOwnerAdmin` are restricted (at the moment I always do this manually but with #31 we'll start automating this), I mean usually operators cannot manipulate the models of those admin classes. We can and we should make also those admin classes multitenant but we can work on it in a separate issue or make it a GCI task because it's not very urgent.

f I misunderstood something or something is not clear let me know.
