### ISSUE TITLE
[enhancement] Add a method to the User to invalidate organization cache

### ISSUE THREAD

**Issue by pandafy** [openwisp/openwisp-users#322]
Add a method in the User model that allow invalidation the organizations cache of the user. 

**Possible Solution**

```python
# In openwisp_users.base.models.AbstractUser
def _invalidate_organization_organizations_dict(self):
     cache.delete('user_{}_organizations'.format(self.pk))
     try:
        del user.organizations_managed
    except AttributeError:
        pass
    try:
        del user.organizations_owned
    except AttributeError:
        pass

```

Then we can use this method in the `openwisp_users.apps.OpenwispUsersConfig`: 
https://github.com/openwisp/openwisp-users/blob/09a617e5b7b56836a4d45893a0865fa19a929d52/openwisp_users/apps.py#L118-L135

**Comment by nemesisdesign** [comment]
@Aryamanz29 the second part of this issue is missing from your PR, please can you proceed?

I am referring to:

> Then we can use this method in the openwisp_users.apps.OpenwispUsersConfig:

**Comment by Aryamanz29** [comment]
> @Aryamanz29 the second part of this issue is missing from your PR, please can you proceed?
> 
> I am referring to:
> 
> > Then we can use this method in the openwisp_users.apps.OpenwispUsersConfig:

@nemesisdesign  I have already used this method in `openwisp_users.app.OpenwispUserConfig`, see here : https://github.com/openwisp/openwisp-users/pull/330/files#diff-e7dc19a2f4b3dc4fd06892a0e23b73cae8c005bc2a3326fe0990ff0f1850e509R162-R163
