### ISSUE TITLE
[bug] User in 2 organizations sees his user listed twice if not superuser

### ISSUE THREAD

**Issue by okraits** [openwisp/openwisp-users#324]
I have the following situation:

* 2 organizations A and B:

![grafik](https://user-images.githubusercontent.com/5543887/180463765-d460da51-7cb4-47ac-bb11-259fd24612fc.png)

* An user `org_admin` who is admin in both organizations:

![grafik](https://user-images.githubusercontent.com/5543887/180464422-7806402c-f490-4a8a-8b64-c6a51caa6956.png)

* The superuser `admin` sees the following users:

![grafik](https://user-images.githubusercontent.com/5543887/180464915-8582297d-3242-4f07-b138-56d637d394db.png)

* But the user `org_admin` sees the following users:

![grafik](https://user-images.githubusercontent.com/5543887/180465108-9a1f5ced-524c-4288-bd35-949e31d53cd3.png)

The same user is listed twice, it's the same id.

* if the user `org_admin` clicks on one of those two entries, the query fails:

![grafik](https://user-images.githubusercontent.com/5543887/180465541-20302aa1-c494-4193-afd4-2ba9920c934e.png)

* if the user `org_admin` has superuser status, everything is fine:

![grafik](https://user-images.githubusercontent.com/5543887/180466088-32dd5aed-ec14-4500-8f29-a305f17e715f.png)

This happens with openwisp-users 1.0.2.

**Comment by nemesisdesign** [comment]
I think this patch https://github.com/openwisp/openwisp-users/pull/343  would fix this issue, but I couldn't complete it yet.

**Comment by Rishabh07gupta** [comment]
@nemesisdesign @okraits The above error indicates that you have more than one record in the DB related to the specific parameter you passed while querying using get(). So instead of using get() you should use filter().
Assign me this task if this helpful to you.
