### ISSUE TITLE
[admin] Only organizationuser objects which have admin=True should be able to manage their organization in the admin

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-users#34]
It could happen that a user which has `is_staff` set to `True` becomes member of another organization because he wants to use some service (implemented in other openwisp modules) of that organization as a user, but at the moment we can't let that happen because in the moment he become member of that organization he will also be able to edit the objects of that organization from the admin.

To solve this problem, we should change the code so that only `OrganizationUser` objects which are both member of an organization and have `is_admin` set to `True` are able to see and edit the objects of that organization.

When `OrganizationUser.is_admin` is set to `False` the user won't be allowed to see anything related to that organization in the admin.

**Comment by OltarzewskiK** [comment]
Can I take this issue?

**Comment by nemesisdesign** [comment]
@OltarzewskiK yes you can :-)

**Comment by OltarzewskiK** [comment]
@nemesisdesign Ok, I will try to get down work in weekend, but gci is coming soon, so after beginning of google code in I would like to focus on contest's tasks, so Can I send PR (if I won't finish it before gci) after competition?

**Comment by nemesisdesign** [comment]
@OltarzewskiK up to you, there are no requirements in open source, contributors contribute when they can. If someone else comes up and can finish this issue before you do we shouldn't prevent them from doing so, because it's more important to fix the issue than who fixes it, I'll send you some suggestions via PM

**Comment by OltarzewskiK** [comment]
@nemesisdesign For doing this task should I use existing function for example [this](https://github.com/openwisp/openwisp-users/blob/master/openwisp_users/multitenancy.py#L27) or create new?

**Comment by OltarzewskiK** [comment]
@nemesisdesign Are you sure that I have to change this method: https://github.com/openwisp/openwisp-users/blob/master/openwisp_users/admin.py#L195-L213 [the class](https://github.com/openwisp/openwisp-users/blob/master/openwisp_users/admin.py#L123) where it is referring to is I think `User`not `OrganizationUser`, so have I to create new class in the `admin`?
