### ISSUE TITLE
[deps] Update allauth to 0.60.0

### ISSUE THREAD

**Issue by nemesifier** [openwisp/openwisp-users#370]
Update allauth to 0.60.0. We'll have to make sure tests pass or if not, fix any failing test.

**Comment by arup1221** [comment]
@nemesifier  could you please check my Pull request !  --  #371

**Comment by nemesifier** [comment]
Solved: https://github.com/openwisp/openwisp-users/commit/99c5c7d84e78f4655714c9ce000cd63942d38a9d.
