### ISSUE TITLE
Move MultitenantAdminMixin from openwisp-utils to openwisp-users

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-users#45]
See https://github.com/openwisp/openwisp-utils/issues/14.

**Comment by OltarzewskiK** [comment]
@nemesisdesign I have to move MultitenantAdminMixin to admin.py or rather to mixins.py?

**Comment by nemesisdesign** [comment]
@OltarzewskiK I think we could go as far as to move all the multitenancy admin logic to `multitenancy.py` which should make it really obvious

**Comment by OltarzewskiK** [comment]
@nemesisdesign :+1: I will try to deal with it tomorrow, because now is quite late
