### ISSUE TITLE
[docs] Document MultitenantAdminMixin multitenant_shared_relations and parent

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-users#58]
``MultitenantAdminMixin`` has two attributes:

- ``multitenant_shared_relations``: the description is totally unclear
- ``parent`` this is not documented, I added this to allow having multi-tenancy for models which don't have directly an organization field, but have a parent model which does have the field

**Comment by ankit-kumar-dwivedi** [comment]
@nemesisdesign Can I work on this issue? :)

**Comment by nemesisdesign** [comment]
@ankit-kumar-dwivedi this is more a reminder for myself.
