### ISSUE TITLE
[ux] Server error 500 received instead form indicating error

### ISSUE THREAD

**Issue by atb00ker** [openwisp/openwisp-users#76]
When adding a new organization and selecting an organization user from a different organization server error 500 is recevied.

Expected: Form indicating "please select user from same organization"

**Comment by IAmAMissingColon** [comment]
Hello Is This Error Still Present ?

**Comment by NoumbissiValere** [comment]
@IAmAMissingColon it seems no one is working on the issue. so you are free to work on it and make a pull request.

**Comment by IAmAMissingColon** [comment]
Okay :)

**Comment by NoumbissiValere** [comment]
@IAmAMissingColon  try to first replicate the problem on the `openwisp-user` module.

**Comment by NoumbissiValere** [comment]
@IAmAMissingColon  you try the following steps.
- first install this module in development mode and see that it runs without any problems
- create an organization. maybe called `org1`
- create a user. maybe called `org1_user` and add this user to this `org1` organization
- create the second organization maybe called `org2`. while creating this organization add `org1_user` to it as an organization user. you should see `error 500`. with this error, try to play around with the code, you might start with the `admin.py` . i think you should find something that will help you.

**Comment by IAmAMissingColon** [comment]
OKAY !!!! 

THANK YOU :)!!

**Comment by NoumbissiValere** [comment]
you are welcome @IAmAMissingColon .
Another thing which can guide you to quickly find which file to modify is to look at the `traceback error` which is thrown at your terminal when the `error 500` occurs.

**Comment by IAmAMissingColon** [comment]
> @IAmAMissingColon you try the following steps.
> 
>     * first install this module in development mode and see that it runs without any problems
> 
>     * create an organization. maybe called `org1`
> 
>     * create a user. maybe called `org1_user` and add this user to this `org1` organization
> 
>     * create the second organization maybe called `org2`. while creating this organization add `org1_user` to it as an organization user. you should see `error 500`. with this error, try to play around with the code, you might start with the `admin.py` . i think you should find something that will help you.

OK!, I'm Seeing Organization Missmatch

**Comment by AshutoshAgrawal2004** [comment]
Can I work on this task?

**Comment by atb00ker** [comment]
@AshutoshAgrawal2004 No need to ask, just claim it on GCI, if it's claimable, please feel free to do it! :smile:

**Comment by IAmAMissingColon** [comment]
Sure @AshutoshAgrawal2004 :smile:

**Comment by AshutoshAgrawal2004** [comment]
@atb00ker @IAmAMissingColon Thanks! I will try my best to fix this bug
