### ISSUE TITLE
[ux] overlapping words

### ISSUE THREAD

**Issue by atb00ker** [openwisp/openwisp-users#93]
![talent](https://user-images.githubusercontent.com/24985760/71403547-146dbb00-2656-11ea-8206-97103c6e634f.png)

I've seen this in other places as well, but we need to find the reason behind this overlapping content and how to fix it here in the organization users view! :smile:

**Comment by nemesisdesign** [comment]
Which page is this?

**Comment by atb00ker** [comment]
It's the change organization users page : `admin/openwisp_users/organizationuser/<id>`.

**Comment by nepython** [comment]
@atb00ker, this issue also seems to ahve been resolved.:smile: 
![image](https://user-images.githubusercontent.com/54471024/75577409-ebb7d680-5a87-11ea-9780-542ec4c45b68.png)

**Comment by atb00ker** [comment]
I don't think any GCI student look into it.
It might be fixed upstream, might be thanks to UI problem in django and they fixed it, in anycase, I can't see it either, thanks for helping me clean up outdated issues! :smile:
